---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    networks:
      default:
        ipv4_address: 172.23.0.51
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr:/config
      - /your/folder_for/TV:/tv
      - /your/folder_for/downloads:/downloads
    ports:
      - 6001:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    networks:
      default:
        ipv4_address: 172.23.0.52
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - /your/folder_for/Films:/movies
      - /media/storage/downloadclient-downloads:/downloads
    ports:
      - 6002:7878
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    networks:
      default:
        ipv4_address: 172.23.0.53
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022
      - WEBUI_PORT=6003
    volumes:
      - ./qbittorrent:/config
      - /your/folder_for/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6003:6003
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    networks:
      default:
        ipv4_address: 172.23.0.54
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./jackett/config:/config
      - /your/folder_for/downloads:/downloads
    ports:
      - 6004:9117
    restart: unless-stopped

  searcharr:
    container_name: searcharr
    image: toddrob/searcharr:latest
    networks:
      default:
        ipv4_address: 172.23.0.55
    volumes:
      - ./searcharr/data:/app/data
      - ./searcharr/logs:/app/logs
      - ./searcharr/settings.py:/app/settings.py
    environment:
      - TZ=Europe/Kiev
    restart: unless-stopped
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    networks:
      default:
        ipv4_address: 172.23.0.56 
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Kiev
      - PLEX_CLAIM=your_tocken
      #- ADVERTISE_IP=http://192.168.205.4:32400/
    #hostname: plexserver.home-server.local
    volumes:
      - ./plex/database:/config
      - ./plex/transcode:/transcode
      - /your/folder_for/content/:/data
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      default:
        ipv4_address: 172.23.0.57
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./overseerr:/config
    ports:
      - 6005:5055
    restart: unless-stopped

networks:
  default:
    external: true
    name: media-proxy