---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    networks:
      default:
        ipv4_address: 172.23.0.51
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr:/config
      - /media/storage/TV:/tv
      - /media/storage/downloadclient-downloads:/downloads
    ports:
      - 6001:8989
    restart: unless-stopped
  searcharr:
    container_name: searcharr
    image: toddrob/searcharr:latest
    networks:
      default:
        ipv4_address: 172.23.0.58
    volumes:
      - ./searcharr/data:/app/data
      - ./searcharr/logs:/app/logs
      - ./searcharr/settings.py:/app/settings.py
    environment:
      - TZ=Europe/Kiev
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    networks:
      default:
        ipv4_address: 172.23.0.57
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./jellyseerr:/config
    ports:
      - 6005:5055
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    networks:
      default:
        ipv4_address: 172.23.0.52
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - /media/storage/Films:/movies
      - /media/storage/downloadclient-downloads:/downloads
    ports:
      - 6002:7878
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    networks:
      default:
        ipv4_address: 172.23.0.53
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - UMASK_SET=022
      - WEBUI_PORT=6003
    volumes:
      - ./qbittorrent:/config
      - /media/storage/downloadclient-downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6003:6003
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    networks:
      default:
        ipv4_address: 172.23.0.54
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      # - RUN_OPTS=run options here #optional
    volumes:
      - ./jackett/config:/config
      - /media/storage/downloadclient-downloads:/downloads
    ports:
      - 6004:9117
    restart: unless-stopped
    
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      default:
        ipv4_address: 172.23.0.59 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=Europe/Kiev
      - JELLYFIN_PublishedServerUrl=10.10.30.2 #optional
    volumes:
      - ./jellyfin:/config
      - /media/storage/TV:/data/tvshows
      - /media/storage/Films:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

networks:
  default:
    external: true
    name: media-proxy
