version: '3.3'
services:
    speedtest-tracker:
      container_name: speedtest
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.speedtest.rule=Host(`speedtest.local`)"
        - "traefik.http.routers.speedtest.entrypoints=web"
        - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - './config:/config'
        - './web:/etc/ssl/web'
      image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
      restart: unless-stopped
      networks:
        - local
networks:
  local:
    external: true