version: "3.9"
services:
  torrserver:
    image: torrserver/torrserver
    container_name: torrserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Kiev
      - PUID=1000
      - PGID=1000
      - TORRSERVER_CONFIG=/config
      - TORRSERVER_DATABASE=/data/torrserver.db
    volumes:
      - ./torrserver/config:/config
      - ./torrserver/data:/data
      - ./downloads:/downloads
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.torrserver.rule=Host(`torrserver.local`)"
      - "traefik.http.routers.torrserver.entrypoints=web"
      - "traefik.http.services.torrserver.loadbalancer.server.port=8090"
    networks:
      - local
networks:
  local:
    external: true