---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    uptime: true
    cputemp: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank
- datetime:
    text_size: xl
    format:
      timeZone: Europe/Kiev
      dateStyle: long
      timeStyle: long
- openmeteo:
    label: Odesa # optional
    latitude: 52.52
    longitude: 13.41
    timezone: Europe/Kiev # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
